### PR TITLE
Add queries

### PR DESCRIPTION
**Pull request by stephanbuys**
This discards history, which isn't a major concern to me. @KodrAus I'm going to let this one sit for you to merge, then I'll start working (doing squashed commits as requested).

### CODE REVIEW

**Comment by KodrAus** [comment]
Looks good! I'll merge this in once the build goes through. Speaking of they're pretty slow now that everything is in together. I don't want to hold up your progress so I'll do something about that.

Maybe we should start [caching packages](https://docs.travis-ci.com/user/caching/#Rust-Cargo-cache)?

**Comment by stephanbuys** [comment]
Sounds good to me, I can flip the switch while I'm at it? (looks simple enough)

**Comment by KodrAus** [comment]
No worries, I just opened up a new PR so you don't have a new build to wait for.

I've also added a label for the queries crate we can use to assign issues and PRs to (I'm trying to assign the change and crate labels so we could generate changelogs or something from them one day, but could do it retrospectively too).

**Comment by KodrAus** [comment]
You might also find the [integration tests](https://github.com/elastic-rs/elastic/tree/master/tests) interesting. I've only gotten as far as stubbing one out though [here](https://github.com/elastic-rs/elastic/blob/master/tests/run/src/search/no_index.rs). We should definitely start adding some for queries once we integrate it in `elastic`.

**Pull request merged**
