### PR TITLE
Single 2018 edition crate

### PR DESCRIPTION
**Pull request by KodrAus**
This PR updates the codebase to the 2018 edition and merges the distinct crates into one. We're hitting limitations with multiple crates for very little benefit, so merging them will let us hide more implementation details, and use standard types across the distinct features.

### CODE REVIEW

**Comment by KodrAus** [comment]
I'm also working in some `7.0` support into this PR, but while our integration test coverage is still sparse (we should try convert all the response parsing tests into proper integration tests) there are probably still a lot of holes.

**Comment by KodrAus** [comment]
The docs need some more work, they still refer to the old crate layout, but once this is green I'll merge it in so we have something consistent to work off.

**Comment by KodrAus** [comment]
Ok there’s progress on the build. We have an issue with the sniffed nodes test where it’s not properly shutting down, even though it should be.

I’m also interested in a few more module refactorings:

```rust
mod endpoints {}
mod params {}

mod client {
    mod requests {}
    mod responses {}
}

mod http {
    mod sender {}
    mod receiver {}
}
```

So that it’s clearer where the high-level and low-level details live.

**Comment by mwilliammyers** [comment]
Wow, this looks awesome! Much easier to navigate. 

Thanks for this PR and such an amazing crate!

**Pull request merged**
